spring:
   cloud:
      config:
         uri: http://localhost:9999
   application:
      name: Customer-Service
server:
   port: 8080
#eureka:
#   instance:
#      hostname: localhost
#   client:
#      serviceUrl:
#         defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
#spring:
#   profile: localhost