server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    appname: EUREKA_SERVER_1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/