server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    appname: EUREKA_SERVER_2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/